### ISSUE TITLE
Run GitHub actions on push

### ISSUE THREAD

**Issue by marijnvanwezel** [hexil-org/hexer#31]
Currently, workflows are only run whenever an event in a `pull_request` occurs. I think we also should run the workflows on the `push` event to get more immediate feedback about the code we are working on, without having to make a pull request for it.

**Comment by Stef-Gijsberts** [comment]
I always immediately create a pull request, even if I'm still working on something (in that case I'll just set it to 'draft').

But for others it may be useful.

Will this cause the workflow to run twice in case a Pull Request is opened?

**Comment by marijnvanwezel** [comment]
Yes, it will.

**Comment by marijnvanwezel** [comment]
I have pushed this for now, but feel free to change it if you think there is a better option. I will leave this issue open for now.

**Comment by marijnvanwezel** [comment]
> Yes, it will.

Actually, I don't think opening a pull request will actually trigger duplicate actions. However, if you do a push and then immediately open a pull request for your changes, the not yet finished workflow will also be listed on the pull request.

**Comment by Stef-Gijsberts** [comment]
Can't the `pull_request` trigger be just removed if we have the `push` trigger?

**Comment by marijnvanwezel** [comment]
We can also opt to remove the `push` trigger from our workflows. Since we have `workflow_dispatch` as our triggers now, people can manually run the workflow if they want to, but by default workflows are only run on pull requests.

**Comment by Stef-Gijsberts** [comment]
Either works for me, so I'll let you decide :)

**Comment by Stef-Gijsberts** [comment]
I think both choices are ok, so I chose one. I just removed the `push` trigger from our workflows, if that turns out to be a bad idea then we can reverse it later.
