### ISSUE TITLE
Fix badge in README

### ISSUE THREAD

**Issue by Stef-Gijsberts** [hexil-org/hexer#71]
Right now, the badge links to https://github.com/hexil-org/hexer/actions/workflows/check.yaml. But it should link to https://github.com/hexil-org/hexer/actions/workflows/deploy.yaml instead.

**Comment by marijnvanwezel** [comment]
This is fixed in `main`, right?

**Comment by Stef-Gijsberts** [comment]
It does not seem to be

https://user-images.githubusercontent.com/55096788/186000700-86b07ee3-8ac9-45b2-841e-2d42fcc0ffc7.mp4
